name: Test code

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: 'test code'
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        # go-version: '1.19' # use as fallback if no version in go.mod

    # testing
    - name: run test
      run: go test -v ./...
